// Code generated by tygo. DO NOT EDIT.
/**
  * GENERATED FILE
  * 
  * DO NOT EDIT
  */

//////////
// source: favourite_media.go

export interface FavouriteMedia {
  ID: string /* UUID */;
  UserID: string /* UUID */;
  MediaID: string /* UUID */;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: favourite_person.go

export interface FavouritePerson {
  ID: string /* UUID */;
  UserID: string /* UUID */;
  PersonID: string /* UUID */;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: image.go

export interface Image {
  ID: string /* UUID */;
  MediaID: string /* UUID */;
  Height: number /* int32 */;
  Width: number /* int32 */;
}

//////////
// source: job.go

export interface Job {
  ID: string /* UUID */;
  Parent?: string /* UUID */;
  Priority: number /* int16 */;
  Status: JobStatusEnum;
  Data?: string;
  Outcome?: string;
  Created: Date;
  Modified: Date;
  JobType: JobTypeEnum;
}

//////////
// source: job_status_enum.go

export type JobStatusEnum = string;
export const JobStatusEnum_NotStarted: JobStatusEnum = "not_started";
export const JobStatusEnum_InProgress: JobStatusEnum = "in_progress";
export const JobStatusEnum_Failed: JobStatusEnum = "failed";
export const JobStatusEnum_Completed: JobStatusEnum = "completed";
export const JobStatusEnum_Cancelled: JobStatusEnum = "cancelled";

//////////
// source: job_type_enum.go

export type JobTypeEnum = string;
export const JobTypeEnum_UpdateExistingVideos: JobTypeEnum = "update_existing_videos";
export const JobTypeEnum_ScanPath: JobTypeEnum = "scan_path";
export const JobTypeEnum_GenerateChecksum: JobTypeEnum = "generate_checksum";
export const JobTypeEnum_GenerateThumbnail: JobTypeEnum = "generate_thumbnail";
export const JobTypeEnum_ScanLibrary: JobTypeEnum = "scan_library";
export const JobTypeEnum_RefreshMetadata: JobTypeEnum = "refresh_metadata";
export const JobTypeEnum_RefreshLibraryMetadata: JobTypeEnum = "refresh_library_metadata";
export const JobTypeEnum_GenerateChapters: JobTypeEnum = "generate_chapters";
export const JobTypeEnum_GenerateLibraryChapters: JobTypeEnum = "generate_library_chapters";

//////////
// source: library.go

export interface Library {
  ID: string /* UUID */;
  Name: string;
  LibraryType: LibraryTypeEnum;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: library_path.go

export interface LibraryPath {
  ID: string /* UUID */;
  LibraryID: string /* UUID */;
  Path: string;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: library_type_enum.go

export type LibraryTypeEnum = string;
export const LibraryTypeEnum_Image: LibraryTypeEnum = "image";
export const LibraryTypeEnum_Video: LibraryTypeEnum = "video";
export const LibraryTypeEnum_Mixed: LibraryTypeEnum = "mixed";

//////////
// source: media.go

export interface Media {
  ID: string /* UUID */;
  LibraryPathID: string /* UUID */;
  Path: string;
  Title: string;
  MediaType: MediaTypeEnum;
  Size: number /* int64 */;
  Checksum?: string;
  Added: Date;
  Deleted: boolean;
  Exists: boolean;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: media_person.go

export interface MediaPerson {
  ID: string /* UUID */;
  Created: Date;
  Modified: Date;
  MediaID: string /* UUID */;
  PersonID: string /* UUID */;
  GhostID?: number /* int32 */;
}

//////////
// source: media_progress.go

export interface MediaProgress {
  ID: string /* UUID */;
  UserID: string /* UUID */;
  MediaID: string /* UUID */;
  Timestamp: number /* float64 */;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: media_relation.go

export interface MediaRelation {
  ID: string /* UUID */;
  MediaID: string /* UUID */;
  RelatedTo: string /* UUID */;
  RelationType: MediaRelationTypeEnum;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
  Metadata?: string;
}

//////////
// source: media_relation_type_enum.go

export type MediaRelationTypeEnum = string;
export const MediaRelationTypeEnum_Thumbnail: MediaRelationTypeEnum = "thumbnail";
export const MediaRelationTypeEnum_Chapter: MediaRelationTypeEnum = "chapter";
export const MediaRelationTypeEnum_Media: MediaRelationTypeEnum = "media";

//////////
// source: media_tag.go

export interface MediaTag {
  ID: string /* UUID */;
  Created: Date;
  Modified: Date;
  MediaID: string /* UUID */;
  TagID: string /* UUID */;
  GhostID?: number /* int32 */;
}

//////////
// source: media_type_enum.go

export type MediaTypeEnum = string;
export const MediaTypeEnum_Primary: MediaTypeEnum = "primary";
export const MediaTypeEnum_Asset: MediaTypeEnum = "asset";

//////////
// source: person.go

export interface Person {
  ID: string /* UUID */;
  Name: string;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: person_alias.go

export interface PersonAlias {
  ID: string /* UUID */;
  Alias: string;
  Created: Date;
  Modified: Date;
  PersonID: string /* UUID */;
}

//////////
// source: playlist.go

export interface Playlist {
  ID: string /* UUID */;
  Name: string;
  UserID: string /* UUID */;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: playlist_media.go

export interface PlaylistMedia {
  ID: string /* UUID */;
  PlaylistID: string /* UUID */;
  MediaID: string /* UUID */;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: schema_migrations.go

export interface SchemaMigrations {
  Version: number /* int64 */;
  Dirty: boolean;
}

//////////
// source: tag.go

export interface Tag {
  ID: string /* UUID */;
  Name: string;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: tag_alias.go

export interface TagAlias {
  ID: string /* UUID */;
  Alias: string;
  Created: Date;
  Modified: Date;
  TagID: string /* UUID */;
}

//////////
// source: user.go

export interface User {
  ID: string /* UUID */;
  Username: string;
  Password: string;
  Active: boolean;
  Created: Date;
  Modified: Date;
  GhostID?: number /* int32 */;
}

//////////
// source: video.go

export interface Video {
  ID: string /* UUID */;
  MediaID: string /* UUID */;
  Height: number /* int32 */;
  Width: number /* int32 */;
  Runtime: number /* float64 */;
  GhostID?: number /* int32 */;
}
